name: openwrt-package-auto-sync

on:
  push:
    branches:
      -master
  workflow_dispatch:
  schedule:
    - cron: 0 */24 * * *   # 每隔12小时
  watch:                                                        # 监视操作
    types: [started]                                            # 点击 Star 之后
    
env: 
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  SCKEY: ${{ secrets.SCKEY }}
  TZ: Asia/Shanghai
  SRC_REPO: https://github.com/281677160/openwrt-package.git
  TARGET_REPO: https://${{ secrets.REPO_TOKEN }}@github.com/dylan8888/openwrt-package.git

jobs:
  build:
    runs-on: Ubuntu-20.04

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [master,19.07,openwrt-18.06,openwrt-18.06-k5.4]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "dylan8888+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b ${{matrix.target}} ${{SRC_REPO}} ${{matrix.target}}
        git remote add target ${{TARGET_REPO}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *
    
    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE
        git add .
        git commit -m "同步源码于$(TZ='Asia/Shanghai' date +%Y年%m月%d号-%H点%M分)"
        git push --quiet target HEAD:${{matrix.target}} || exit 0
